### PR TITLE
add arm64 macos build

### PR DESCRIPTION
**Pull request by ianhi**
hopefully fixes: https://github.com/AllenCellModeling/aicspylibczi/issues/101

### CODE REVIEW

**Review by JacksonMaxfield — COMMENTED** [review]
I have no idea if we should update the global job env or if we should update the specific task env, line 96

**Comment by ianhi** [comment]
oops i may have put in the wrong place

**Comment by ianhi** [comment]
ah ya beat me to it

**Comment by psobolewskiPhD** [comment]
Y'all lemme know (how) and I can test anything M1 related!

**Comment by ianhi** [comment]
I don't think this should affect any of the tests here so the only way to check is to run the deply script and try to use the generated wheel

**Comment by JacksonMaxfield** [comment]
> I don't think this should affect any of the tests here so the only way to check is to run the deply script and try to use the generated wheel

Agree. I leave this PR approve and deploy to @toloudis

**Review by JacksonMaxfield — APPROVED** [review]
It makes sense to me :shrug: :shrug: :shrug: I leave to @toloudis for deploy

**Comment by toloudis** [comment]
I think we can test prior to merging by changing the conditions that the action runs under, then watch actions and see if anything fails.  if the build succeeds, then we can reset the conditions and merge and move forward.
Otherwise I can just merge and go for it blind instead of half blind :)

**Comment by toloudis** [comment]
i'll just do it, let's build it and see.

**Review by toloudis — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Should just show up here right?
https://pypi.org/project/aicspylibczi/#files

**Comment by ianhi** [comment]
> Should just show up here right?
I think you can only get it from: https://github.com/AllenCellModeling/aicspylibczi/suites/4994059858/artifacts/146261793

**Comment by JacksonMaxfield** [comment]
Whenever we push a new version, likely just a patch release, it _should_ also be pushed to pypi

**Comment by toloudis** [comment]
yes - it won't go to pypi until we do a version bump and trigger the release publish process

**Comment by psobolewskiPhD** [comment]
Bad news, unless I screwed something up:
```
pip install /Users/piotrsobolewski/Downloads/artifact/aicspylibczi-3.0.4-cp3-cp39-macosx_11_0_arm64.whl
Processing /Users/piotrsobolewski/Downloads/artifact/aicspylibczi-3.0.4-cp39-cp39-macosx_11_0_arm64.whl
Requirement already satisfied: numpy>=1.14.1 in /Users/piotrsobolewski/Dev/miniforge3/envs/napari-env/lib/python3.9/site-packages (from aicspylibczi==3.0.4) (1.22.0)
Installing collected packages: aicspylibczi
Successfully installed aicspylibczi-3.0.4
```
But:
```
> lipo -info _aicspylibczi.cpython-39-darwin.so
Non-fat file: _aicspylibczi.cpython-39-darwin.so is architecture: x86_64
```

**Comment by JacksonMaxfield** [comment]
Sorry, why is this bad news? It looks like that install worked!

**Comment by psobolewskiPhD** [comment]
The install worked, but the library in the wheel is x86-64:
`Non-fat file: _aicspylibczi.cpython-39-darwin.so is architecture: x86_64`
It should be arm64:
`artifact/aicspylibczi-3.0.4-cp3-cp39-macosx_11_0_arm64.whl`
So the wheel/bundling is making a "thing" for arm64, but it's not actually compiling an arm64 version of the library and placing it inside the bundle.

**Comment by JacksonMaxfield** [comment]
Here are the docs from cibuildwheel themselves if you find any insights in them... i can't see what went wrong: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

**Comment by JacksonMaxfield** [comment]
And, looking at their direct example. It's the code we had before this PR :confused:

**Comment by psobolewskiPhD** [comment]
I can't say I understand how any of this works. 
I don't get what `cibuildwheel` does, relative to the setup.py/cfg files.
I assume the issue is that when the _aics bit is compiled it's not cross compiled, but just x86.
I've fixed other things to compile by set the cmake flag CMAKE_OSX_ARCHITECTURES to arm64—but this library compiles just fine if i clone the repo. I think it must be something related to cmake because:
https://github.com/AllenCellModeling/aicspylibczi/issues/101#issuecomment-1017252716
Trying to compile via pip also fails.

**Pull request merged**
