### PR TITLE
fix build error related to eigen in libczi

### PR DESCRIPTION
**Pull request by toloudis**
I update libCZI to fix a build issue.  I also simplified the build rules here a bit.  Related to https://github.com/zeiss-microscopy/libCZI/issues/60 for reference.

### CODE REVIEW

**Review by JacksonMaxfield — APPROVED** [review]
Nice work! And a PR into libCZI itself!

**Review by MatteBailey — APPROVED** [review]

**Comment by MatteBailey** [comment]
I was planning on doing a patch release of `aicsimageio` today to release [some updates to the XSLT](https://github.com/AllenCellModeling/aicsimageio/pull/365). Should we get these changes incorporated for that release too?

**Comment by JacksonMaxfield** [comment]
> I was planning on doing a patch release of `aicsimageio` today to release [some updates to the XSLT](https://github.com/AllenCellModeling/aicsimageio/pull/365). Should we get these changes incorporated for that release too?

Technically its a different lib so no real need to. Unless you simply wanted to update the minimum version pin.

**Comment by MatteBailey** [comment]
> > I was planning on doing a patch release of `aicsimageio` today to release [some updates to the XSLT](https://github.com/AllenCellModeling/aicsimageio/pull/365). Should we get these changes incorporated for that release too?
> 
> Technically its a different lib so no real need to. Unless you simply wanted to update the minimum version pin.

That's what I was thinking, but if that's necessary that's fine.

**Review by heeler — APPROVED** [review]
Hi @toloudis, Nice job on updating Eigen, this has been an irritation for a while as it kept us locked at C++14. Just a couple thoughts on this:
- update the CMakeLists.txt form 14 to 17 or 20. There are a lot of nice new features that it would be able to use in the language. (std::filesystem for example), ranges etc. 
- I'd highly recommend moving away from git-submodule approach and towards cmake's FetchContent mechanism. That way it's crazy easy to update versions and the dependencies are all visible in one file, ie no guessing as to how stale things are getting. If I have any time I can take a stab at it but you could easily be waiting for quite a while. 
Nice work.

**Comment by toloudis** [comment]
@heeler I'm not sure I actually updated Eigen - it was an update that broke things. I pinned it according to the version that the libCZI devs recommended for me.   And that dependency is inside the cmake files for libCZI, not in any cmake files that we control.

As for c++17 or 20, I'm all for it if it doesn't break anything in the dependencies.   Kinda neutral on submodule vs cmake fetchcontent.  submodule isn't exactly broken here but I like the newer cmake stuff too.

**Pull request merged**
